modLoader = "javafml"

loaderVersion = "[1,)"

license = "Apache-2.0"

issueTrackerURL="https://github.com/TKFT/World-Preview-TFC/issues"

[[mods]]

modId = "${mod_id}"

version = "${mod_version}"

displayName = "${mod_name}"


logoFile = "../../resources/assets/world_preview_tfc/icon.png"

authors = "Original Mod - Caeruleus Draconis and Taiterio, TFC Port - RustySnail"

description = '''World Preview TFC adds a new tab in the World creation screen to preview a seed. Ported to TFC by RustySnail'''

[[mixins]]

config = "world_preview.mixins.json"

[[dependencies.${ mod_id }]]

modId = "neoforge"

type = "required"

versionRange = "[21.1.213,)"

ordering = "NONE"

side = "BOTH"


[[dependencies.${ mod_id }]]
modId = "minecraft"

type = "required"

versionRange = "${minecraft_version_range}"

ordering = "NONE"

side = "BOTH"

[[dependencies.${ mod_id }]]

modId = "tfc"

type = "required"

versionRange = "[4.0.17,)"

ordering = "AFTER"

side = "BOTH"

[[dependencies.${ mod_id }]]

modId = "world_preview"

type = "incompatible"

versionRange = "[]"

side = "BOTH"